export const CHAT_REQUEST = 'CHAT_REQUEST'
export const CHAT_SUCCESS = 'CHAT_SUCCESS'
export const CHAT_FAIL = 'CHAT_FAIL'
export const CHAT_RESET ='CHAT_RESET'

export const CHAT_LIST_REQUEST = 'CHAT_LIST_REQUEST'
export const CHAT_LIST_SUCCESS = 'CHAT_LIST_SUCCESS'
export const CHAT_LIST_FAIL = 'CHAT_LIST_FAIL'
export const CHAT_LIST_RESET ='CHAT_LIST_RESET'

export const CHAT_DELETE_REQUEST = 'CHAT_DELETE_REQUEST'
export const CHAT_DELETE_SUCCESS = 'CHAT_DELETE_SUCCESS'
export const CHAT_DELETE_FAIL = 'CHAT_DELETE_FAIL'